title: PieceOfRice
logo: /assets/face.jpg
email: rhysharvey99@gmail.com
#description: PieceOfRice Site
color-scheme: auto
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme






platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/PieceOfRice
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/rhys-d-harvey/

navigation:
  - name: Home
    link: /index.html
  - name: CV
    link: /pages/cv.html
  - name: Projects
    link: /pages/projects/projectindex.html
    sublist:
      - name: NeuroEvolution with Mario
        link: /pages/projects/marioevo.html
      - name: Uni Team Project
        link: /pages/projects/teamproject.html
